package domain

import "errors"

var (
	ErrUserNotFound             = errors.New("User Not found")
	ErrNotFound                 = errors.New("Not found")
	ErrConflict                 = errors.New("This email is already in use")
	ErrTokeNotFoundOrExpired    = errors.New("Token Not found or expired")
	ErrInvalidCredentials       = errors.New("Invalid Credentials")
	ErrInvalidRefreshToken      = errors.New("Invalid Refresh Token")
	ErrAlreadyVerified          = errors.New("Email already verified")
	ErrNotVerified              = errors.New("account not verified")
	ErrWeakPassword             = errors.New("Password must be more than 8 characters")
	ErrAccountDeactivated       = errors.New("account has been deactivated")
	ErrNameConflict             = errors.New("This name is alredy in use")
	ErrInvalidFileExtension     = errors.New("This is not a valid image extension %s")
	ErrInvalidTableCapacity     = errors.New("Table capacity must be greater than 0")
	ErrTableNameConflict        = errors.New("A table with this name already exists in this restaurant")
	ErrInvalidTimeSlot          = errors.New("Invalid time slot")
	ErrTableReservation         = errors.New("Table already reserved for this time")
	ErrMaxReservation           = errors.New("You have reached the maximum number of reservations allowed per day")
	ErrPastDates                = errors.New("You cannot make reservations for past dates")
	ErrTableAlreadyBooked       = errors.New("Table already booked for the selected date and time")
	ErrForbidden                = errors.New("Forbidden")
	ErrAlreadyCheckedIn         = errors.New("User Already Checked In")
	ErrReservationNotFound      = errors.New("Reservation Not Found")
	ErrAlreadyCancelled         = errors.New("Reservation Already Cancelled")
	ErrCannotCancel             = errors.New("Cannot cancel reservation less than 24 hours before")
	ErrInvalidDate              = errors.New("Invalid Date")
	ErrTableAvailable           = errors.New("Table is available for booking")
	ErrAlreadyOnWaitlist        = errors.New("You are already on the waitlist")
	ErrPublishing               = errors.New("Error publishing message %s")
	ErrMenuNotFound             = errors.New("Menu Not found")
	ErrCartNotFound             = errors.New("Cart Not found")
	ErrCartItemNotFound         = errors.New("Cart Item Not found")
	ErrMenuNotAvailable         = errors.New("Menu not available at the moment")
	ErrCartIsEmpty              = errors.New("Cart is Empty")
	ErrOrderNotFound            = errors.New("Order Not found")
	ErrInvalidOrderStatus       = errors.New("Invalid Order Status")
	ErrOrderAlreadyPaid         = errors.New("Order is already paid")
	ErrPaymentNotFound          = errors.New("Payment Not found")
	ErrPaymentAmountMismatch    = errors.New("Payment amount mismatch")
	ErrInvalidSignature         = errors.New("Invalid Signature")
	ErrOrderNotPaid             = errors.New("Order has not been paid for")
	ErrRefundAlreadyProcessed   = errors.New("Refund already processed")
	ErrRefundNotFound           = errors.New("Refund Not found")
	ErrRefundIsProcessing       = errors.New("Refund is currently being processed")
	ErrAlreadyRefunded          = errors.New("Order Already Refunded")
	ErrIngredientNotFound       = errors.New("Ingredient Not found")
	ErrCannotExceedCurrentStock = errors.New("Threshold cannot exceed current stock")
	ErrNegativeThreshold        = errors.New("Threshold cannot be negative")
	ErrIngredientAlreadyLinked  = errors.New("Ingredient already linked to menu")
	ErrInvalidIngredientID      = errors.New("Invalid Ingredient ID")
	ErrInvalidQuantity          = errors.New("Quantity cannot be negative")
	ErrInsufficientStock        = errors.New("Insufficient Stock")
	ErrInternalServerError      = errors.New("Internal Server Error")
)
