services:
  postgres:
    image: postgres:16-alpine
    container_name: geritcht-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geritcht_db
    volumes:
      - geritcht_db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: geritcht-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  geritcht-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL
    env_file:
      - ../.env
    command: ["./api"]

   geritcht-notifier:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL
    command: ["./notifier"]
    deploy:
      replicas: 1

  

volumes:
  geritcht_db_data:
  redis-data:
