services:
  geritcht-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - ../.env
    command: ["./api"]
    restart: unless-stopped

  geritcht-notifier:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    command: ["./notifier"]
    restart: unless-stopped
